apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: tools
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgBWb0O9oItHoS3cp4N9PWDuQHU7jzGFwhVPPmMGAc6WY09CIu/1ggiIov2AAzOS/TF2G/Q0G5paLbUutJ938Pu0A17Z91T8J7ck0eXQHDH4OG5bT77Xt4WTCp0sj9nJKJyT5BRMB3VA2/Cgr9wplRjoGAkabqsjNJPL7Ae7N3Igg+dYpNTHi3eOP/M87kguCMI3v9BqKV9YLE3/STtY67sJQEZBcASV40TzzaSzlK7nutHID7LIiNHWNDCnCr2LXPeUVRMQmDntuuquPZ0z0mrSQe3aV35pcFrUvL6hplRLDYoPFsfH901ctJ14yA/lgxp+Z7FUxgsussRgi6R6a6EI1q2fg2NjoCMQ+b2wM8id3+tjPcj0wJ2CH3wlkw+tStHAbc0uMECCDX4zXfdmPxuvzyRtNJOdaVI3/rLBXamal3ubdjN90u+pzgxyMW7JLdLsjKaxGfVaKnPoVQ4Oal70/EMiRGL76rOXAVTc0YmVEOdhumFDFXUekdjnHaPi6XmOoJE+gz8NWyu1LKgiIo8mOkXON7MCVMaDb+poEFV0xzj1O3Hd2HICF5/04pYMJOwM9y9Hb+etMiXCYU7ltbMvUH2fqFX/0DePBKENN+vJmLuvscV9QQ4Fz06Vvm748pvZbGs4RAkHDzxpQmRPwmBwO5iiORbVsdd/ibNyI9npBbW11SVYcu5KXFyt4y0wwXUKkYBTip8OsA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: tools
    type: Opaque

