apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: tools
spec:
  encryptedData:
    DB_PASSWORD: AgBjTEkSkuuZ+A51DC2h/5rDbfM94XbZoVC28s3fksPAyiodLq+qjAZDN7sTrdjAzR3gRMoGr2Sd+Ao+00+zYSr9wSo6U7R1k48Cil4N60WW15xBE4xDFc/Ul9tslpXk5jbSvb5xE/OIakb1HYbyh885cUfUEcK+gyI/yyUKgZ7K756stmCoro3faqMraadp0pAU9cq69nhj9/0mCj6bzg20Lg/F90hz9TKe+CGMYsUjYFgGshs6Eli84lE13ZNTDY6FZJoyjsc++c0/AQxSNlgQDzgY+5O/ZZQ93Op2SkS3BpF+rXxrHv3LFENAy7hlNELfJ5rIvqFZsbWVNQeqgn7JKQGi+vE0FqcWOtxWMHhwLR9TxR83oYaboacif6zXnjSNJU/cjoNOQOjvsebsp2ZWEslArV1mK7hkvMrx83ARm4SPz+sx9uGM68HOygbA3OQnpHifqUpXj2T1G+bPb1PMmji9AvezCr3SGZfY8+/xHJ+buNKmtY8lnRYPvSDz8qV3kg8mAE+O4YF/nVojWLQ6PipMaFOg/WiLBXa23/GjhOeuVjmZ9iyEq5T5KmljvCokVUSIiEo7kaqTNspJBiQxqwWlHoWe3aokZKGkrQWJQ0XDax10/YG/92br7YpdZ8ebYZSfLmZ9DfZjIEWCxqlnqWgxztOEWXdgJnuoSKpzOzf7VwD9KjQEZUPwY+ThKODX9T7oaXFqhw==
    DB_USER: AgC77lGIapgApGOIqqiwBaxQEOonWx1pjwH0PahuFOa4W+nanBA1SJJnqdSbfxMaYmfxpb38HzxpQV+i++76iSS+zZPfXsixi86NPUyDoNDM271eKhSFfrg/rqirswjESiMuiBH5AVKyYZeZss7NgYCFbNEFRqn3Tkzo9PJjl690jP/uL86I4EJLoKWANmwfi2jBnlLO8IbAnvl1XDMZd3WRH4/NG4KvOG+fiTSInvfTOuRBAGzUfbqbjXj2ldHpniUAFGlJC2/Bjl9LOVtOvyC+KJMOt0BOMxPDHOUS8xTHDhAtFLoO4S2rlOR4z6M5UYwGZ4rwsMmAYS8fjwNQKjf0fh33eiRip6Ey673oJxYHnBl6An5ZO8hu2W9qE3D0gYLFGGiI+aNid5UiPsW0V3V5GGch6OUvA7tucHnaIHBi3wdKO2QJI+qcXAoEqd8fjXLpm1ahWqROaj1jg0cqPZLvxlPrjhvI3cV0IY6MRjyJPyLeOLooFZ/jvWna7M+BdaSMGD2CVic4PXkMg9ZM5ETdmHv6FtoHsJTFyvdy5Ut4QGw65SFGEqWvRinDihHkATqGAf0IH7ZxG+rpRmv7wGyXxRCtarezed0VyLsxZABEwB7aoqoMjSuqsfcwa66D5S5633/1JTStymJtTkCBA+3MB94pyBTsqMhV4XQ7q6j8DSmWOYytEYe6Y4CAKc4KV2Vu2z+Esz3NFQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: tools
    type: Opaque

